### ISSUE TITLE
some questions

### ISSUE THREAD

**Issue by Pydataman** [keonlee9420/STYLER#6]
1.in paper, why output of encoder （text_encoding) upsample and downsample?
2. what is the meaning of  text_encoding_neck+pitch_encoding、text_encoding_neck+energy_encoding？
    why not cat？

**Comment by keonlee9420** [comment]
Hi @Pydataman , thanks for your attention.
1. Z_t takes the role of general text hidden representation as in FastSpeech2's. Z_t' is only for predictors and downsampled to balance influence to other audio encodings by applying channel-wise bottleneck from its shrunk hidden size.
2. There is no empirical preference between addition and concatenation. There should be no significant difference when you adopt concatenation instead of addition.

**Comment by Pydataman** [comment]
@keonlee9420 thank you

**Comment by keonlee9420** [comment]
close due to inactivity.
